app:
  datasource:
    host: db
    port: 27017
    user: apms
    password: apms123
    dbname: apms
  security:
    jwt:
      secret: 1nt3rst3ll4r-*-a5tR0
      valid-minute: 90
  server:
    port: 8080
    